-- =============================================
-- Outbox Messages Table
-- Stores messages that need to be published
-- =============================================
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='ARQ_OUTBOX_MESSAGES' AND xtype='U')
BEGIN
    CREATE TABLE [{Initials}_OUTBOX_MESSAGES] (
        [OUT_ID] NVARCHAR(128) NOT NULL,
        [OUT_TOPIC] NVARCHAR(500) NOT NULL,
        [OUT_PAYLOAD] NVARCHAR(MAX) NOT NULL,
        [OUT_SPEC_VERSION] NVARCHAR(20) NOT NULL,
        [OUT_SOURCE] NVARCHAR(200) NOT NULL,
        [OUT_TYPE] NVARCHAR(200) NOT NULL,
        [OUT_TIME] DATETIME2(7) NOT NULL,
        [OUT_DATA_CONTENT_TYPE] NVARCHAR(100) NOT NULL,
        [OUT_TRACE_ID] NVARCHAR(200) NULL,
        [OUT_CREATED_AT] DATETIME2(7) NOT NULL DEFAULT GETUTCDATE(),
        [OUT_PROCESSED_AT] DATETIME2(7) NULL,
        [OUT_RETRY_COUNT] INT NOT NULL DEFAULT 0,
        [OUT_NEX_RETRY_AT] DATETIME2(7) NULL,
        [OUT_ERROR] NVARCHAR(MAX) NULL,
        [OUT_STATUS] INT NOT NULL DEFAULT 0, -- 0=Pending, 1=Processing, 2=Processed, 3=Failed, 4=Dead
        [OUT_ROWVERSION] ROWVERSION NOT NULL,

        -- Granular locking columns for concurrent processing
        [OUT_PROCESSING_INSTANCE_ID] NVARCHAR(256) NULL,
        [OUT_PROCESSING_STARTED_AT] DATETIME2(7) NULL,
        [OUT_PROCESSING_EXPIRED_AT] DATETIME2(7) NULL,

        CONSTRAINT [PK_ARQ_OUTBOX_MESSAGES] PRIMARY KEY CLUSTERED ([OUT_ID] ASC),
        CONSTRAINT [CK_ARQ_OUTBOX_MESSAGES_OUT_STATUS] CHECK ([OUT_STATUS] IN (0, 1, 2, 3, 4)),
        CONSTRAINT [CK_ARQ_OUTBOX_MESSAGES_OUT_RETRY_COUN] CHECK ([OUT_RETRY_COUNT] >= 0)
    )

    -- Create indexes for performance
    CREATE INDEX [IX_ARQ_OUTBOX_MESSAGES_OUT_STATUS_OUT_CREATED_AT] ON [ARQ_OUTBOX_MESSAGES] ([OUT_STATUS], [OUT_CREATED_AT])
    CREATE INDEX [IX_ARQ_OUTBOX_MESSAGES_OUT_STATUS_OUT_NEX_RETRY_AT] ON [ARQ_OUTBOX_MESSAGES] ([OUT_STATUS], [OUT_NEX_RETRY_AT]) WHERE [OUT_NEX_RETRY_AT] IS NOT NULL
    CREATE INDEX [IX_ARQ_OUTBOX_MESSAGES_OUT_TOPIC_OUT_STATUS] ON [ARQ_OUTBOX_MESSAGES] ([OUT_TOPIC], [OUT_STATUS])
    CREATE INDEX [IX_ARQ_OUTBOX_MESSAGES_OUT_CREATED_AT] ON [ARQ_OUTBOX_MESSAGES] ([OUT_CREATED_AT])
    CREATE INDEX [IX_ARQ_OUTBOX_MESSAGES_OUT_PROCESSED_AT] ON [ARQ_OUTBOX_MESSAGES] ([OUT_PROCESSED_AT]) WHERE [OUT_PROCESSED_AT] IS NOT NULL
    CREATE INDEX [IX_ARQ_OUTBOX_MESSAGES_OUT_TRACE_ID] ON [ARQ_OUTBOX_MESSAGES] ([OUT_TRACE_ID]) WHERE [OUT_TRACE_ID] IS NOT NULL

    -- Granular locking indexes
    CREATE INDEX [IX_ARQ_OUTBOX_MESSAGES_OUT_PROCESSING_INSTANCE_ID] ON [ARQ_OUTBOX_MESSAGES] ([OUT_PROCESSING_INSTANCE_ID]) WHERE [OUT_PROCESSING_INSTANCE_ID] IS NOT NULL
    CREATE INDEX [IX_ARQ_OUTBOX_MESSAGES_OUT_PROCESSING_EXPIRED_AT] ON [ARQ_OUTBOX_MESSAGES] ([OUT_PROCESSING_EXPIRED_AT]) WHERE [OUT_PROCESSING_EXPIRED_AT] IS NOT NULL
    CREATE INDEX [IX_ARQ_OUTBOX_MESSAGES_OUT_STATUS_OUT_PROCESSING_EXPIRED_AT] ON [ARQ_OUTBOX_MESSAGES] ([OUT_STATUS], [OUT_PROCESSING_EXPIRED_AT]) WHERE [OUT_PROCESSING_EXPIRED_AT] IS NOT NULL

    PRINT 'Outbox table created with granular locking support'
END
GO